QTU\MarkBundle\Entity\MarkType:
    type: entity
    table: qtu_mark_type
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
