QTU\MarkBundle\Entity\SubjectCourse:
    type: entity
    table: qtu_subject_course
    indexes:
        subject_id:
            columns:
                - subject_id
        term_id:
            columns:
                - term_id
    uniqueConstraints:
        code_UNIQUE:
            columns:
                - code
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
    manyToOne:
        subject:
            targetEntity: QTU\CurriculumBundle\Entity\Subject
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                subject_id:
                    referencedColumnName: id
            orphanRemoval: false
        term:
            targetEntity: Term
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                term_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
