QTU\MarkBundle\Entity\Term:
    type: entity
    table: qtu_term
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        year:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        semester:
            type: boolean
            nullable: false
        orderTerm:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: order_term
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
