services:
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

#    qtu_tkb.example:
#        class: QTU\TkbBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
