QTU\DepartmentMajorBundle\Entity\Major:
    type: entity
    table: qtu_major
    indexes:
        fk_qtu_major_qtu_department1_idx:
            columns:
                - department_id
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        shortname:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        fullname:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        code:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
    manyToOne:
        department:
            targetEntity: Department
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                department_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
