<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author dominhduc dominhdc@gmail.com
 */
/**
 * Class User
 * @package Application\Sonata\UserBundle\Entity
 * @ORM\Table(name="fos_user_user")
 * @ORM\Entity()
*/
class User extends BaseUser
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /** loại tài khoản: gv: 0; sv: 1, khac:3
     * @var integer
     *
     * @ORM\Column(name="qtu_type", type="integer")
     */
    private $qtuType = 0;

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Set qtuType
     *
     * @param integer $type
     * @return User
     */
    public function setQtuType($type)
    {
        $this->qtuType = $type;

        return $this;
    }

    /**
     * Get qtuType
     *
     * @return integer 
     */
    public function getQtuType()
    {
        return $this->qtuType;
    }
}
