QTU\StudentLecturerBundle\Entity\StudentRewardDiscipline:
    type: entity
    table: qtu_student_reward_discipline
    indexes:
        student_id:
            columns:
                - student_id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: integer
            nullable: true
            options:
                unsigned: false
        createdAt:
            type: date
            nullable: true
            column: created_at
        document:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        details:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    manyToOne:
        student:
            targetEntity: Student
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                student_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
