QTU\CurriculumBundle\Entity\CurriculumForClassManagement:
    type: entity
    table: qtu_curriculum_for_class_management
    indexes:
        class_management_id:
            columns:
                - class_management_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    manyToOne:
        classManagement:
            targetEntity: QTU\StudentLecturerBundle\Entity\ClassManagement
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                class_management_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
