QTU\CurriculumBundle\Entity\KnowledgeBlock:
    type: entity
    table: qtu_knowledge_block
    id:
        id:
            type: smallint
            nullable: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
