QTU\CurriculumBundle\Entity\Subject:
    type: entity
    table: qtu_subject
    uniqueConstraints:
        code:
            columns:
                - code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        credit:
            type: smallint
            nullable: false
        ntheory:
            type: smallint
            nullable: false
            options:
                default: 0
        npractice:
            type: smallint
            nullable: false
            options:
                default: 0
        nproject:
            type: smallint
            nullable: false
            options:
                default: 0
        condition:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    manyToOne:
        department:
            targetEntity: QTU\DepartmentMajorBundle\Entity\Department
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                department_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
