QTU\CurriculumBundle\Entity\Subject:
    type: entity
    table: qtu_subject
    uniqueConstraints:
        code:
            columns:
                - code
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        credit:
            type: boolean
            nullable: false
        ntheory:
            type: boolean
            nullable: false
            options:
                default: '0'
        npractice:
            type: boolean
            nullable: false
            options:
                default: '0'
        nproject:
            type: boolean
            nullable: false
            options:
                default: '0'
        condition:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
