QTU\LecturerBundle\Entity\Lecturer:
    type: entity
    table: qtu_lecturer
    indexes:
        fk_qtu_lecture_qtu_department1_idx:
            columns:
                - qtu_department_id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
    manyToOne:
        qtuDepartment:
            targetEntity: QTU\DepartmentMajorBundle\Entity\Department
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                qtu_department_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
