QTU\StudentBundle\Entity\ClassManagementStudent:
    type: entity
    table: qtu_class_management_student
    indexes:
        class_management_id:
            columns:
                - class_management_id
        student_id:
            columns:
                - student_id
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        classManagement:
            targetEntity: ClassManagement
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                class_management_id:
                    referencedColumnName: id
            orphanRemoval: false
        student:
            targetEntity: Student
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                student_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
