parameters:
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

services:
    qtu_department_major.admin.department:
        class: QTU\DepartmentMajorBundle\Admin\DepartmentAdmin
        arguments: [~, QTU\DepartmentMajorBundle\Entity\Department, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: DepartmentMajor, label: Department }
        calls:
            - [setTranslationDomain, [QTUDepartmentMajorBundle]]

    qtu_department_major.admin.major:
        class: QTU\DepartmentMajorBundle\Admin\MajorAdmin
        arguments: [~, QTU\DepartmentMajorBundle\Entity\Major, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: DepartmentMajor, label: Major }
        calls:
            - [setTranslationDomain, [QTUDepartmentMajorBundle]]

    qtu_department_major.admin.major_details:
        class: QTU\DepartmentMajorBundle\Admin\MajorDetailsAdmin
        arguments: [~, QTU\DepartmentMajorBundle\Entity\MajorDetails, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: DepartmentMajor, label: MajorDetails }
        calls:
            - [setTranslationDomain, [QTUDepartmentMajorBundle]]

    qtu_department_major.admin.training_form:
        class: QTU\DepartmentMajorBundle\Admin\TrainingFormAdmin
        arguments: [~, QTU\DepartmentMajorBundle\Entity\TrainingForm, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: DepartmentMajor, label: TrainingForm }
        calls:
            - [setTranslationDomain, [QTUDepartmentMajorBundle]]

    qtu_department_major.admin.training_level:
        class: QTU\DepartmentMajorBundle\Admin\TrainingLevelAdmin
        arguments: [~, QTU\DepartmentMajorBundle\Entity\TrainingLevel, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: DepartmentMajor, label: TrainingLevel }
        calls:
            - [setTranslationDomain, [QTUDepartmentMajorBundle]]
